HelloWorld/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.hello, name = 'home-page'),
]

Recipe_App/urls.py
from django.urls import path
from . import views

app_name = 'Recipe_App'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:Recipe_List_id>/', views.detail, name = 'detail'),
]

TermProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Recipe_App.urls')),
    path('', include('HelloWorld.urls'))
]

HelloWorld/models.py
from django.db import models

# Create your models here.

Recipe_App/models.py
from django.db import models

# Create your models here.
class Recipe_List(models.Model):
    name_text = models.CharField(max_length=30)
    ingredient_text = models.TextField()
    instruction_text = models.TextField()

HelloWorld/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def hello(request):
    return render(request, 'HelloWorld/hello.html')

Recipe_App/views.py
from django.shortcuts import render, get_object_or_404
# from django.http import HttpResponse
# from django.template import loader
# from django.http import Http404

# Create your views here.
from .models import Recipe_List


def index(request):
    all_recipes = Recipe_List.objects.order_by('id')[:]
    #    template = loader.get_template('Recipe_App/index.html')
    context = {
        'all_recipes': all_recipes,
    }
    #    return HttpResponse(template.render(context, request))
    return render(request, 'Recipe_App/index.html', context)


#    output = '\n '.join([str(i + 1) + '.) ' + q.name_text for i, q in enumerate(all_recipes)])
#    return HttpResponse(output)

def detail(request, Recipe_List_id):
    recipe = get_object_or_404(Recipe_List, pk=Recipe_List_id)
    instructions = recipe.instruction_text
    instruction_list = instructions.split('\n')
    #    try:
    #        recipe = Recipe_List.objects.get(pk = Recipe_List_id)
    #    except Recipe_List.DoesNotExist:
    #        raise Http404("Recipe does not exist")
    return render(request, 'Recipe_App/detail.html', {'recipe': recipe, 'instruction_list': instruction_list})
#    return HttpResponse('You\'re looking at recipe number ' + str(Recipe_List_id))

HelloWorld/templates/HelloWorld/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello World</title>
</head>
<body>
<h1>Hello World</h1>

</body>
</html>

Recipe_App/templates/Recipe_App/detail.html
<!DOCTYPE html>
<html>
    <h1>{{ recipe.name_text }}</h1>

    <h4>{{ recipe.ingredient_text }}</h4>

    {% if instruction_list %}
        <ul>
        {% for i in instruction_list %}
            <p>{{ i }}</p>
        {% endfor %}
        </ul>
    {% else %}
        <p> no recipe found </p>
    {% endif %}
    <p><a href="{% url 'Recipe_App:index' %}"> Home</a></p>
</html>

Recipe_App/templates/Recipe_App/index.html
<!DOCTYPE html>
<html>
    {% if all_recipes %}
        <ul>
        {% for recipe in all_recipes %}
            <li><a href="{% url 'Recipe_App:detail' recipe.id %}">{{ recipe.name_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No recipes are available.</p>
    {% endif %}
</html>